install:
  - ps: Install-Product node 10.6.0
  - yarn install --frozen-lockfile

build_script:
  - yarn build
  - cd build
  - aws s3 sync . s3://github-viewer.jabbar-web.com --delete

cache:
  - node_modules